/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-06-09 03:24:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.mainPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import poly.util.CmmUtil;
import java.util.List;
import java.util.ArrayList;
import poly.dto.AttAnalysDTO;
import poly.dto.AttMonthAnaDTO;
import poly.util.CmmUtil;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/view/mainPage/oTop.jsp", Long.valueOf(1623198924374L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("poly.dto.AttAnalysDTO");
    _jspx_imports_classes.add("poly.dto.AttMonthAnaDTO");
    _jspx_imports_classes.add("poly.util.CmmUtil");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

    	String aname = CmmUtil.nvl((String)session.getAttribute("aname"));
    	String aemail= (String)session.getAttribute("aemail");
    	String toDay = CmmUtil.nvl((String) request.getAttribute("toDay"));
        List<AttAnalysDTO> rList = (List<AttAnalysDTO>) request.getAttribute("rList");
        String empCount = (String) request.getAttribute("empCount");
        int empAttCount = (Integer) request.getAttribute("empAttCount");
    
      out.write("    \r\n");
      out.write("    ");

    if(aemail == null){
    	response.sendRedirect("/user/sessioCheck.do");	
    }
    
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>OGENTAE_MAINPAGE</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("\t<!-- 차트 링크 -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto:400,700\">\r\n");
      out.write("    <!-- https://fonts.google.com/specimen/Roboto -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./resources/css/fontawesome.min.css\">\r\n");
      out.write("    <!-- https://fontawesome.com/ -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./resources/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- https://getbootstrap.com/ -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./resources/css/templatemo-style.css\">\r\n");
      out.write("    <!-- 제이쿼리 플러그인 CDN -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("    <!--라이브 차트 JS 시작-->\r\n");
      out.write("    <script src=\"./resources/js/liveChart.js\"></script>\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"http://code.highcharts.com/highcharts.js\"></script>\r\n");
      out.write("\t<script src=\"http://code.highcharts.com/highcharts-more.js\"></script>\r\n");
      out.write("\t<script src=\"http://code.highcharts.com/modules/exporting.js\"></script>\r\n");
      out.write("\t<!-- Latest compiled and minified JavaScript -->\r\n");
      out.write("\t<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- 라이브차트 js 끝 -->\r\n");
      out.write("</head>\r\n");
      out.write("<!--div 테이블 CSS-->\r\n");
      out.write("<style>\r\n");
      out.write("        .divTable{\r\n");
      out.write("        display: table; width: 100%;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        color : white;\r\n");
      out.write("        }\r\n");
      out.write("        .divTableRow {\r\n");
      out.write("        display: table-row;\r\n");
      out.write("        }\r\n");
      out.write("        .divTableHeading {\r\n");
      out.write("        background-color: #EEE; display: table-header-group;\r\n");
      out.write("        }\r\n");
      out.write("        /*./divTableHead 랑 .divTableCell 의 스타일이 같아야 안깨짐 */\r\n");
      out.write("        .divTableHead{\r\n");
      out.write("        border: 1px solid #999999; display: table-cell; padding: 3px 10px; background-color: black;\r\n");
      out.write("        } \r\n");
      out.write("        .divTableCell{\r\n");
      out.write("        border: 1px solid #999999; display: table-cell; padding: 3px 10px;\r\n");
      out.write("        }\r\n");
      out.write("        /*./divTableHead 랑 .divTableCell 의 스타일이 같아야 안깨짐 */\r\n");
      out.write("        .divTableHeading {\r\n");
      out.write("        background-color: #EEE; display: table-header-group; font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        .divTableFoot { background-color: #EEE; display: table-footer-group; font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        .divTableBody {\r\n");
      out.write("        display: table-row-group\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("       <div>\r\n");
      out.write("\t\t<!-- 오근태 탑 탑!!-->\r\n");
      out.write("\t\t");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("    <script src=\"/resources/js/jquery-3.3.1.min.js\"></script>\n");
      out.write("    <!-- https://jquery.com/download/ -->\n");
      out.write("    <script src=\"/resources/js/moment.min.js\"></script>\n");
      out.write("    <!-- https://momentjs.com/ -->\n");
      out.write("    <script src=\"/resources/js/Chart.min.js\"></script>\n");
      out.write("    <!-- http://www.chartjs.org/docs/latest/ -->\n");
      out.write("    <script src=\"/resources/js/bootstrap.min.js\"></script>\n");
      out.write("    <!-- https://getbootstrap.com/ -->\n");
      out.write("    <script src=\"/resources/js/tooplate-scripts.js\"></script>\n");
      out.write("<body>\n");
      out.write("    <nav class=\"navbar navbar-expand-xl\">\n");
      out.write("            <div class=\"container h-100\">\n");
      out.write("                <a class=\"navbar-brand\" href=\"opencvIndex.do\"> \n");
      out.write("                    <h1 class=\"tm-site-title mb-0\">O-GeunTae</h1>\n");
      out.write("                </a>\n");
      out.write("                <button class=\"navbar-toggler ml-auto mr-0\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"\n");
      out.write("                    aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("              <i class=\"fas fa-bars tm-nav-icon\"></i>\n");
      out.write("                </button>\n");
      out.write("\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("                    <ul class=\"navbar-nav mx-auto h-100\">\n");
      out.write("                        <li class=\"nav-item dropdown\">\n");
      out.write("\n");
      out.write("                            <a class=\"nav-link dropdown-toggle\" href=\"/opencvIndex.do\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\"\n");
      out.write("                                aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("                                <i class=\"fas fa-cog\"></i>\n");
      out.write("                                <span>\n");
      out.write("                                    대쉬보드\n");
      out.write("                                </span>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                         <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link active\" href=\"imgCheckPage.do\">\n");
      out.write("                                <i class=\"fas fa-tachometer-alt\"></i>\n");
      out.write("                                출근체크\n");
      out.write("                                <span class=\"sr-only\">(current)</span>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link\" href=\"empMange.do\">\n");
      out.write("                                <i class=\"far fa-user\"></i>\n");
      out.write("                                직원관리\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link\" href=\"sendMail.do\">\n");
      out.write("                                <i class=\"far fa-file-alt\"></i>\n");
      out.write("                                메일발송\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("<!--                         <li class=\"nav-item dropdown\">\n");
      out.write("                            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\"\n");
      out.write("                                aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("                                <i class=\"fas fa-cog\"></i>\n");
      out.write("                                <span>\n");
      out.write("                                    프로그램관리 <i class=\"fas fa-angle-down\"></i>\n");
      out.write("                                </span>\n");
      out.write("                            </a> -->\n");
      out.write("                            <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("                                <a class=\"dropdown-item\" href=\"#\">Profile</a>\n");
      out.write("                                <a class=\"dropdown-item\" href=\"#\">Billing</a>\n");
      out.write("                                <a class=\"dropdown-item\" href=\"#\">Customize</a>\n");
      out.write("                            </div>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                    <ul class=\"navbar-nav\">\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link d-block\" href=\"user/logOut.do\">\n");
      out.write("                                <b>로그아웃</b>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t<!-- 탑 영역 끝-->\r\n");
      out.write("\t   </div>\r\n");
      out.write("\t   \r\n");
      out.write("<body id=\"reportsPage\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"\" id=\"home\">\r\n");
      out.write("<!--####################################################  로그인 유저 정보#################################-->\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                    <p class=\"text-white mt-5 mb-5\">환영합니다. <b>");
      out.print(aname );
      out.write("님</b></p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("<!--################################################## 지각자 분석 차트 #################################-->\r\n");
      out.write("            <div class=\"row tm-content-row\">\r\n");
      out.write("                <div class=\"col-sm-12 col-md-12 col-lg-6 col-xl-6 tm-block-col\">\r\n");
      out.write("                    <div class=\"tm-bg-primary-dark tm-block\">\r\n");
      out.write("                        <h2 class=\"tm-block-title\">2021년 지각자 분석</h2>\r\n");
      out.write("                        <div class = \"container\"></div>\r\n");
      out.write("                        <canvas id=\"myChart\"></canvas>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("<!--#############################################시스템 성능  ###########################################-->                \r\n");
      out.write("                <div class=\"col-sm-12 col-md-12 col-lg-6 col-xl-6 tm-block-col\">\r\n");
      out.write("                    <div class=\"tm-bg-primary-dark tm-block\">\r\n");
      out.write("<!--################################ 성능 확인용 통신 끊기면 생성 안되고 과부하면 그래프 높이 뜀########################-->\r\n");
      out.write("\t\t\t\t\t\t<!-- 성능 차트 -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"container-fluid\" id=\"data-container\"></div>\r\n");
      out.write("<!--################################################### 차트 ############################################-->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>       \r\n");
      out.write("<!--############################################ 출근자 뛰우는 창#############################################-->                           \r\n");
      out.write("                <div class=\"col-12 tm-block-col\">\r\n");
      out.write("                    <div class=\"tm-bg-primary-dark tm-block tm-block-taller tm-block-scroll\">\r\n");
      out.write("                        <h2 class=\"tm-block-title\">[ ");
      out.print(toDay );
      out.write(" ] 출근리스트 \r\n");
      out.write("                        \t<br>( 총원 / 출근인원수 : ");
      out.print(empCount );
      out.write("명 / ");
      out.print(empAttCount );
      out.write(" 명 )</h2>\r\n");
      out.write("                        \t<div> \r\n");
      out.write("                        \t<!--<a>CSV 만들기</a>  --> \r\n");
      out.write("                        \t</div>\r\n");
      out.write("<!--@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  테이블 영역@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"divTable\" style=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    <!-- 테이블 머리 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t    <div class=\"divTableHead\">사원번호</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"divTableHead\">이름</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"divTableHead\">성별</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"divTableHead\">주소</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"divTableHead\">생년월일</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"divTableHead\">출근시간</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"divTableHead\">비고</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--테이블 바디-->\t\r\n");
      out.write("\t\t\t\t\t\t\t    <div class=\"divTableBody\">\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

												 for(AttAnalysDTO e : rList){
													 String bgColor ="";
													 if(e.getLate_Check().equals("지각")){
														  bgColor = "#FF0000";
													 } else{bgColor = "#0000FF";}
												
      out.write("   \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- 테이블 로우 -->\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t <div class=\"divTableRow\" id=\"rowBgColor\" style=\"background-color: ");
      out.print(bgColor );
      out.write("\">     \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t       <div class=\"divTableCell\" class=\"empno\">");
      out.print(e.getEmpno() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t       <div class=\"divTableCell\" class=\"ename\">");
      out.print(e.getEname() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t       <div class=\"divTableCell\" class=\"sex\">");
      out.print(e.getSex() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t       <div class=\"divTableCell\" class=\"addrs\">");
      out.print(e.getAddrs() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t       <div class=\"divTableCell\" class=\"bday\">");
      out.print(e.getBday() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t       <div class=\"divTableCell\" class=\"attdate\">");
      out.print(e.getAtt_date() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t       <div class=\"divTableCell\" class=\"latecheck\">");
      out.print(e.getLate_Check() );
      out.write("</div>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t           </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        ");

												  }
												
      out.write("  \t\r\n");
      out.write("\t\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("<!--@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  테이블 영역@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@-->\r\n");
      out.write("                 </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <footer class=\"tm-footer row tm-mt-small\">\r\n");
      out.write("            <div class=\"col-12 font-weight-light\">\r\n");
      out.write("                <p class=\"text-center text-white mb-0 px-4 small\">\r\n");
      out.write("<!--                     Copyright &copy; <b>2018</b> All rights reserved. \r\n");
      out.write("                    \r\n");
      out.write("                    Design: <a rel=\"nofollow noopener\" href=\"https://templatemo.com\" class=\"tm-footer-link\">Template Mo</a>\r\n");
      out.write("                </p> -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write(" <!-- 지각자 분석 차트-->\r\n");
      out.write("<script th:inline=\"javascript\">\r\n");
      out.write("var ctx = document.getElementById('myChart').getContext('2d');\r\n");
      out.write("var utilityChart = new Chart(ctx, {\r\n");
      out.write("    // The type of chart we want to create\r\n");
      out.write("    type: 'bar',\r\n");
      out.write(" \r\n");
      out.write("    // The data for our dataset\r\n");
      out.write("    data: {\r\n");
      out.write("        labels: ['1월', '2월', '3월', '4월', '5월', '6월', '7월','8월','9월','10월','11월','12월'],\r\n");
      out.write("        datasets: [{\r\n");
      out.write("            label: '월 별 지각자 현황',\r\n");
      out.write("            backgroundColor: 'rgb(245, 166, 35)',\r\n");
      out.write("            borderColor: 'rgb(255, 255, 255)',\r\n");
      out.write("            data: [\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${jan}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${feb}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mar}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${may}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${jun}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${jul}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${aug}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sep}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${oct}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nov}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dec}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"]\r\n");
      out.write("        }]\r\n");
      out.write("    },\r\n");
      out.write(" \r\n");
      out.write("    // Configuration options\r\n");
      out.write("    options: {\r\n");
      out.write("        legend: {\r\n");
      out.write("             labels: {\r\n");
      out.write("                  fontColor: 'white' // label color\r\n");
      out.write("                 }\r\n");
      out.write("              },\r\n");
      out.write("        scales: {\r\n");
      out.write("            // y축\r\n");
      out.write("            yAxes: [{\r\n");
      out.write("                ticks: {\r\n");
      out.write("                    beginAtZero:false,\r\n");
      out.write("                    fontColor:'white' // y축 폰트 color\r\n");
      out.write("                }\r\n");
      out.write("             }],\r\n");
      out.write("             // x축\r\n");
      out.write("             xAxes: [{\r\n");
      out.write("                ticks: {\r\n");
      out.write("                    beginAtZero:false,\r\n");
      out.write("                    fontColor:'white' // x축 폰트 color\r\n");
      out.write("                }\r\n");
      out.write("             }]\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
