/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-06-09 00:39:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.mainPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import poly.dto.EmpDTO;
import static poly.util.CmmUtil.nvl;
import java.util.List;
import java.util.ArrayList;
import poly.util.CmmUtil;

public final class sendMail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/view/mainPage/oTop.jsp", Long.valueOf(1623198924374L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("static poly.util.CmmUtil.nvl");
    _jspx_imports_classes.add("poly.util.CmmUtil");
    _jspx_imports_classes.add("poly.dto.EmpDTO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("    ");

    List<EmpDTO> rList = (List<EmpDTO>)request.getAttribute("rList");
    String aemail= (String)session.getAttribute("aemail");
    
      out.write("\n");
      out.write("   ");

    if(aemail == null){
    	response.sendRedirect("/user/sessioCheck.do");	
    }
    
      out.write("\n");
      out.write("    \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>MailPage</title>\n");
      out.write("<link\n");
      out.write("      rel=\"stylesheet\"\n");
      out.write("      href=\"https://fonts.googleapis.com/css?family=Roboto:400,700\"\n");
      out.write("    />\n");
      out.write("    <!-- https://fonts.google.com/specimen/Roboto -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/fontawesome.min.css\" />\n");
      out.write("    <!-- https://fontawesome.com/ -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/bootstrap.min.css\" />\n");
      out.write("    <!-- https://getbootstrap.com/ -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/templatemo-style.css\">\n");
      out.write("    <!--\n");
      out.write("\tProduct Admin CSS Template\n");
      out.write("\thttps://templatemo.com/tm-524-product-admin\n");
      out.write("\t-->\n");
      out.write("</head>\n");
      out.write("       <div>\n");
      out.write("\t\t<!-- 오근태 탑 탑!!-->\n");
      out.write("\t\t");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("    <script src=\"/resources/js/jquery-3.3.1.min.js\"></script>\n");
      out.write("    <!-- https://jquery.com/download/ -->\n");
      out.write("    <script src=\"/resources/js/moment.min.js\"></script>\n");
      out.write("    <!-- https://momentjs.com/ -->\n");
      out.write("    <script src=\"/resources/js/Chart.min.js\"></script>\n");
      out.write("    <!-- http://www.chartjs.org/docs/latest/ -->\n");
      out.write("    <script src=\"/resources/js/bootstrap.min.js\"></script>\n");
      out.write("    <!-- https://getbootstrap.com/ -->\n");
      out.write("    <script src=\"/resources/js/tooplate-scripts.js\"></script>\n");
      out.write("<body>\n");
      out.write("    <nav class=\"navbar navbar-expand-xl\">\n");
      out.write("            <div class=\"container h-100\">\n");
      out.write("                <a class=\"navbar-brand\" href=\"opencvIndex.do\"> \n");
      out.write("                    <h1 class=\"tm-site-title mb-0\">O-GeunTae</h1>\n");
      out.write("                </a>\n");
      out.write("                <button class=\"navbar-toggler ml-auto mr-0\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"\n");
      out.write("                    aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("              <i class=\"fas fa-bars tm-nav-icon\"></i>\n");
      out.write("                </button>\n");
      out.write("\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("                    <ul class=\"navbar-nav mx-auto h-100\">\n");
      out.write("                        <li class=\"nav-item dropdown\">\n");
      out.write("\n");
      out.write("                            <a class=\"nav-link dropdown-toggle\" href=\"/opencvIndex.do\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\"\n");
      out.write("                                aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("                                <i class=\"fas fa-cog\"></i>\n");
      out.write("                                <span>\n");
      out.write("                                    대쉬보드\n");
      out.write("                                </span>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                         <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link active\" href=\"imgCheckPage.do\">\n");
      out.write("                                <i class=\"fas fa-tachometer-alt\"></i>\n");
      out.write("                                출근체크\n");
      out.write("                                <span class=\"sr-only\">(current)</span>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link\" href=\"empMange.do\">\n");
      out.write("                                <i class=\"far fa-user\"></i>\n");
      out.write("                                직원관리\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link\" href=\"sendMail.do\">\n");
      out.write("                                <i class=\"far fa-file-alt\"></i>\n");
      out.write("                                메일발송\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("<!--                         <li class=\"nav-item dropdown\">\n");
      out.write("                            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\"\n");
      out.write("                                aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("                                <i class=\"fas fa-cog\"></i>\n");
      out.write("                                <span>\n");
      out.write("                                    프로그램관리 <i class=\"fas fa-angle-down\"></i>\n");
      out.write("                                </span>\n");
      out.write("                            </a> -->\n");
      out.write("                            <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("                                <a class=\"dropdown-item\" href=\"#\">Profile</a>\n");
      out.write("                                <a class=\"dropdown-item\" href=\"#\">Billing</a>\n");
      out.write("                                <a class=\"dropdown-item\" href=\"#\">Customize</a>\n");
      out.write("                            </div>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                    <ul class=\"navbar-nav\">\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link d-block\" href=\"user/logOut.do\">\n");
      out.write("                                <b>로그아웃</b>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("\t\t<!-- 탑 영역 끝-->\n");
      out.write("\t   </div>\n");
      out.write("<body id=\"reportsPage\">\n");
      out.write("    <div class=\"\" id=\"home\">\n");
      out.write("\n");
      out.write("\t   \n");
      out.write("      <div class=\"container mt-5\">\n");
      out.write("        <div class=\"row tm-content-row\">\n");
      out.write("          <div class=\"col-12 tm-block-col\">\n");
      out.write("            <div class=\"tm-bg-primary-dark tm-block tm-block-h-auto\">\n");
      out.write("              <h2 class=\"tm-block-title\">메일 발송</h2>\n");
      out.write("              <p class=\"text-white\">받는 사람</p>\n");
      out.write("              \n");
      out.write("           <form action=\"/sendMailProc.do\" class=\"tm-signup-form row\" method=\"post\">\n");
      out.write("           \n");
      out.write("              <select class=\"custom-select\" name=\"eemail\">\n");
      out.write("                <option value=\"0\">받을 사람을 선택해주세요.</option>\n");
      out.write("                ");
 
                	for(EmpDTO e : rList) {
                
      out.write("\n");
      out.write("                <option value=\"");
      out.print(e.getEemail());
      out.write('"');
      out.write('>');
      out.print(nvl(e.getEname()) );
      out.write('(');
      out.print(nvl(e.getEemail()) );
      out.write(")</option>\n");
      out.write("\t\t\t\t");

                	}
				
      out.write("\n");
      out.write("              </select>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- row -->\n");
      out.write("        <div class=\"row tm-content-row\">\n");
      out.write("\n");
      out.write("          <div class=\"form-group col-lg-12\">\n");
      out.write("            <div class=\"tm-bg-primary-dark tm-block tm-block-settings\">\n");
      out.write("              <h2 class=\"tm-block-title\">메일 작성</h2>\n");
      out.write("              \n");
      out.write("    <!-- 폼 테그!!!!!!!!!!!!! -->\n");
      out.write("    \n");
      out.write("       \n");
      out.write("                <div class=\"form-group col-lg-12 p-0\">\n");
      out.write("                  <label for=\"name\">제목</label>\n");
      out.write("                  <input\n");
      out.write("                    id=\"title\"\n");
      out.write("                    name=\"title\"\n");
      out.write("                    type=\"text\"\n");
      out.write("                    class=\"form-control validate\"\n");
      out.write("                  />\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("               <div class=\"form-group mb-3\">\n");
      out.write("                    <label\n");
      out.write("                      for=\"description\"\n");
      out.write("                      >내용</label\n");
      out.write("                    >\n");
      out.write("                    <textarea\n");
      out.write("                      class=\"form-control validate\"\n");
      out.write("                      rows=\"3\"\n");
      out.write("                      required\n");
      out.write("                      name=\"contents\"\n");
      out.write("                    ></textarea>\n");
      out.write("                  </div>\n");
      out.write("               \n");
      out.write("                <div class=\"form-group col-lg-12\">\n");
      out.write("                  <label class=\"tm-hide-sm\">&nbsp;</label>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-12\">\n");
      out.write("                  <button\n");
      out.write("                    type=\"submit\"\n");
      out.write("                    class=\"btn btn-primary btn-block text-uppercase\">\n");
      out.write("                    메일 발송\n");
      out.write("                  </button>\n");
      out.write("                </div>\n");
      out.write("              </form>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <footer class=\"tm-footer row tm-mt-small\">\n");
      out.write("        <div class=\"col-12 font-weight-light\">\n");
      out.write("          <p class=\"text-center text-white mb-0 px-4 small\">\n");
      out.write("            Copyright &copy; <b>2018</b> All rights reserved. \n");
      out.write("            \n");
      out.write("            Design: <a rel=\"nofollow noopener\" href=\"https://templatemo.com\" class=\"tm-footer-link\">Template Mo</a>\n");
      out.write("          </p>\n");
      out.write("        </div>\n");
      out.write("      </footer>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script src=\"/resources/js/jquery-3.3.1.min.js\"></script>\n");
      out.write("    <!-- https://jquery.com/download/ -->\n");
      out.write("    <script src=\"/resources/js/bootstrap.min.js\"></script>\n");
      out.write("    <!-- https://getbootstrap.com/ -->\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
